server.port=8081
server.servlet.context-path=/back_PFE
spring.datasource.url=jdbc:postgresql://localhost:5432/newdata
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emaildessai0@gmail.com
spring.mail.password=hyxy yabx ocke ston
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



minio.url=http://127.0.0.1:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=dossier

spring.jpa.hibernate.ddl-auto = update
